# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('slug', models.SlugField(help_text='\u6839\u636ename\u751f\u6210\uff0c\u7528\u4e8e\u751f\u6210\u9875\u9762URL,\u5fc5\u987b\u552f\u4e00', unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('meta_keywords', models.CharField(help_text='meta\u5173\u952e\u8bcd\uff0c\u6709\u5229\u4e8eSEO,\u7528\u9017\u53f7\u5206\u9694', max_length=255, verbose_name='Meta \u5173\u952e\u8bcd')),
                ('meta_description', models.CharField(help_text='meta\u63cf\u8ff0', max_length=255, verbose_name='Meta \u63cf\u8ff0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('slug', models.SlugField(help_text='\u6839\u636ename\u751f\u6210\uff0c\u7528\u4e8e\u751f\u6210\u9875\u9762URL,\u5fc5\u987b\u552f\u4e00', max_length=255, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(max_length=50, verbose_name='\u54c1\u724c')),
                ('sku', models.CharField(max_length=50, verbose_name='\u8ba1\u91cf\u5355\u4f4d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u4ef7\u683c')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='\u65e7\u4ef7\u683c')),
                ('image', models.ImageField(max_length=50, upload_to=b'', verbose_name='\u56fe\u7247')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u8bbe\u4e3a\u6fc0\u6d3b')),
                ('is_bestseller', models.BooleanField(default=True, verbose_name='\u8bbe\u4e3a\u7545\u9500')),
                ('is_featured', models.BooleanField(default=True, verbose_name='\u8bbe\u4e3a\u63a8\u8350')),
                ('quantity', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('meta_keywords', models.CharField(help_text='Meta\u5173\u952e\u8bcd\u6807\u7b7e,\u9017\u53f7\u5206\u9694', max_length=255, verbose_name='Meta\u5173\u952e\u8bcd')),
                ('meta_description', models.CharField(help_text='meta \u63cf\u8ff0\u6807\u7b7e', max_length=255, verbose_name='Meta\u63cf\u8ff0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('categories', models.ManyToManyField(to='catalog.Category')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'product',
            },
        ),
    ]
